### ISSUE TITLE
開発環境を整える

### ISSUE THREAD

**Issue by udcxx** [udcxx/portfolio#1]
2020年版ポートフォリオを作成する前に、開発環境を整備する

## ToDo

- [x] .scssをコンパイルできるようにする・ウォッチも
- [x] .html / .js に変更があったら dist ディレクトリにコピーさせる
- [x] 画像ファイルに変更があったら、圧縮して dist ディレクトリにコピーさせる
- [x] BrowserSyncでページプレビューできるようにする
- [x] git pushをhookにしてサーバーにデプロイできるようにする

## 参考サイト

* 以前scssコンパイル・BrowserSyncを導入したときの記事
    * https://blog.udcxx.me/article/200120/html-template/
* 普通のレンタルサーバーでもgit pushしたらコード自動ビルド→自動デプロイさせる
    * https://qiita.com/Sn005/items/e78791f58a1466027026
* node-sassの設定
    * https://sioyaki.com/entry/2016/05/02/153303
* BrowserSyncの設定
    * https://browsersync.io/docs/options
* html / js / 画像ファイルのコピーなどの処理
     * https://olein-design.com/blog/build-webpage-by-npm-script

**Comment by udcxx** [comment]
## 0228 done.

- [x] git ftp のインストール
    * コマンド叩けばデプロイできた！
- [x] huskyのインストール
- [x] node-scssのインストール
- [x] browser-syncのインストール

**Comment by udcxx** [comment]
## 0308 done.

- [x] imagemin系インストール、imgmin.js を作成し画像圧縮＆ディレクトリコピーができるように
- [x] cpx のインストール、html / js のディレクトリコピーができるように
- [x] watch / onchange で監視できるように
- [x] その他 npm-scripts の調整

**Comment by udcxx** [comment]
## 0404 done.

- [x] npm-watchだと正規表現でディレクトリ指定が上手くできなかったので、監視は全部（BrowserSync以外）npm-onchangeで書き直した

**Comment by udcxx** [comment]
## 0408 done.

- [x] git push でサーバーにデプロイまで可能に！！

**Comment by udcxx** [comment]
## git-ftp はgit管理してないとアップされない

dist ディレクトリを管理外にしたせいで、サーバー上からもファイルが消えてしまった
